# Generated by Django 2.1 on 2019-05-30 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_jk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_keys', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='authkey',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='refreshkey',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Key'),
        ),
    ]
