# Generated by Django 2.1 on 2019-06-13 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_jk', '0002_auto_20190530_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='authkey',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_key', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='refreshkey',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_key', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
